---
- name: Deploy PHP Application on MIG
  hosts: php_servers
  connection: local
  become: yes
  
  tasks:
    - name: Install Docker
      shell: |
        gcloud compute ssh {{ inventory_hostname }} --zone={{ hostvars[inventory_hostname].zone }} --command="
          sudo apt-get update -y
          sudo apt-get install -y docker.io
          sudo systemctl enable docker
          sudo systemctl start docker
        "

    - name: Install gcloud SDK for Docker auth
      shell: |
        gcloud compute ssh {{ inventory_hostname }} --zone={{ hostvars[inventory_hostname].zone }} --command="
          echo 'deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main' | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get install -y apt-transport-https ca-certificates gnupg
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk
        "

    - name: Authenticate Docker with Artifact Registry
      shell: |
        gcloud compute ssh {{ inventory_hostname }} --zone={{ hostvars[inventory_hostname].zone }} --command="
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          sudo docker run -d --name php-app -p 80:80 us-central1-docker.pkg.dev/siva-477505/php-app/php-app:v1
        "

